services:
  bpdl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bpdl

    network_mode: "container:gluetun"

    stdin_open: true
    tty: true

    volumes:
      - ./config:/config
      - /mnt/usb-a/drive/downloads:/downloads

    restart: "no"

  bpdl-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bpdl-web
    entrypoint: ["bpdl-web"]

    network_mode: "container:gluetun"

    volumes:
      - ./config:/config
      - /mnt/usb-a/drive/downloads:/downloads

    restart: unless-stopped
